# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0016_gamesets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesets',
            name='chat_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
