# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0018_auto_20171009_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('classification_one', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=2)),
                ('classification_two', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=1)),
                ('complete_one', models.BooleanField(default=False)),
                ('complete_two', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=45)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('classification_one', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=2)),
                ('classification_two', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=1)),
                ('classification_three', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=3)),
                ('complete_one', models.BooleanField(default=False)),
                ('complete_two', models.BooleanField(default=False)),
                ('complete_three', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=25)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(1, b'blue'), (2, b'red'), (3, b'yellow'), (4, b'lab')], default=1)),
                ('count', models.IntegerField(default=0)),
                ('complete', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Player')),
            ],
        ),
        migrations.RenameModel(
            old_name='GameSets',
            new_name='GameSet',
        ),
        migrations.RemoveField(
            model_name='researchobjective',
            name='player',
        ),
        migrations.RemoveField(
            model_name='researchobjective',
            name='research_resources',
        ),
        migrations.DeleteModel(
            name='ResearchObjective',
        ),
        migrations.DeleteModel(
            name='ResearchResource',
        ),
    ]
