# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0019_auto_20171014_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='Game.Player'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='Game.Player'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='Game.Player'),
        ),
    ]
