# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0020_auto_20171014_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='_ticks',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='complete',
        ),
        migrations.AddField(
            model_name='game',
            name='total_ticks',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='conference',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='score',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='tick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tick', to='Game.Game'),
        ),
    ]
