# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0021_auto_20171022_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_tick', to='Game.Game'),
        ),
    ]
