# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0022_auto_20171022_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertick',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playertick',
            name='tick',
        ),
        migrations.RemoveField(
            model_name='playertick',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='playertick',
            name='tick_number',
            field=models.IntegerField(default=0),
        ),
    ]
