# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0024_auto_20171029_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertick',
            name='is_attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_blue_capability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_blue_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_manager_sanction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_peer_sanction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_red_capability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_red_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_yellow_capability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='playertick',
            name='is_yellow_security',
            field=models.BooleanField(default=True),
        ),
    ]
