# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0025_auto_20171107_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTickDup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_number', models.IntegerField(default=0)),
                ('action', models.IntegerField(choices=[(0, b'The player did not move.'), (1, b'sanctioned player'), (6, b'activated security resource blue'), (8, b'activated security resource red'), (7, b'activated security resource yellow'), (3, b'completed research objective'), (5, b'clicked the pass button')], default=0)),
                ('is_red_security', models.BooleanField(default=True)),
                ('is_blue_security', models.BooleanField(default=True)),
                ('is_yellow_security', models.BooleanField(default=True)),
                ('is_blue_capability', models.BooleanField(default=True)),
                ('is_yellow_capability', models.BooleanField(default=True)),
                ('is_red_capability', models.BooleanField(default=True)),
                ('is_attack', models.IntegerField(default=0)),
                ('is_peer_sanction', models.BooleanField(default=False)),
                ('is_manager_sanction', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Player')),
            ],
        ),
    ]
