# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0029_auto_20171113_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertickdatabase',
            name='number_of_attacks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
