# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0030_auto_20171114_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertickdatabase',
            name='time_to_fix_capability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='time_to_fix_immunity',
            field=models.IntegerField(default=0),
        ),
    ]
