# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0032_playertickdatabase_dospert_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertickdatabase',
            name='number_of_immunities_available',
            field=models.IntegerField(default=0),
        ),
    ]
