# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0033_playertickdatabase_number_of_immunities_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertickdatabase',
            name='dospert_score_ethical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='dospert_score_financial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='dospert_score_health_safety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='dospert_score_recreational',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playertickdatabase',
            name='dospert_score_social',
            field=models.IntegerField(default=0),
        ),
    ]
